[package]
name = "microbit"
version = "0.0.1"
authors = [
    "Erik Svensson <erik.public@gmail.com>"
    ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utilities = { path = "../utilities" }
nrf52833-pac = "0.9"
nrf52833-hal = "0.12"
cortex-m = "0.6"
cortex-m-rt = "0.6"
cortex-m-rtic = "0.5"
bbqueue = "0.4"
ieee802154 = "0.3"
esercom = { git = "https://github.com/blueluna/esercom.git", branch = "master" }
psila-nrf52 = { git = "https://github.com/blueluna/psila-nrf52.git", features = ["52833"] }
psila-data = { git = "https://github.com/blueluna/psila.git", features = ["core"] }
aes = { version = "0.7" }
ccm = { version = "0.4", default-features = false }
defmt = "0.2"
defmt-rtt = "0.2"
panic-probe = { version = "0.2", features = ["print-defmt"] }

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.3"

[features]
# set logging levels here
default = [
  "defmt-default",
]

# do NOT modify these features
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []
